= Support Platform
Hartl Anna, Hautzmayer Sheila
1.0.1, 2021-01-28: Functional Specification Document
ifndef::imagesdir[:imagesdir: images]
:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

== Current State
When customers have a problem with Vinitor they have to call or send an email to the owners.
Owners inform their customers about news by sending out emails.

== CLD
[plantuml,align=left]
----
include::plantuml/cld_vinitor.puml[]
----

== ERD


== Problem Definition
The owners can not spread news and information to all their customers in an easy way. Emails can get lost and overseen by customers.
Customers can not interact with each other. When a problem occurs often it has to be explained countless times.
The owners are overwhelmed with the calls and emails.

== Use-case-diagram
[plantuml,align=left]
----
include::plantuml/use_case_customer.puml[]
----
[plantuml,align=left]
----
include::plantuml/use_case_owner.puml[]
----

== Use-cases (Functional Requirements)
* Users can log in/log out of the application
* Users can report bugs
* Users can upvote reported bugs
* Owners can comment on the reported bugs
* Owner has statics over bugs
* Users can send direct messages to the owners (vise versa)
* Owners can post announcements (Can be liked, disliked and commented by users)
* Announcements can have dates -> calendar
* Owners can post learning material like blog posts and video tutorials (Users can watch them)
* Owners can make a survey/vote (Users can vote)
* Announcements can be connected with email and social media


== Non Functional Requirements
* Security
* Usability
* Accessibility
* Stability
* Coexistence

== Goal
The support platform should help with the cooperation and collaboration of customers and owners by simplifying the communication.

== Framework
IDE: Intellij

Programming Languages: Angular (Front end), Java (Back end)

Database language: MariaDB (open source SQL)

VCS: GitHub

Organization: YouTrack

== Acceptance criteria
Every use case needs to be fulfilled. The platform needs to run smoothly for every customer.



