@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:Customer:

rectangle Support-Platform{
Customer -> (can report and upvote bugs)
 Customer --> (watch tutorials and blogs)
 Customer --> (takes part in surveys)
 Customer --> (can comment and like)
}
@enduml
