@startuml
'https://plantuml.com/use-case-diagram


left to right direction
:Owner:

rectangle Support-Platform{
 Owner ---> (see statistics of survey and bug report)
 Owner ---> (can announce features and events)
 Owner ---> (can comment on bug reports)
}
@enduml